import Foundation

/// Supplies a synthetic content section – pages generated by a plugin rather than loaded
/// from source files – into the build so the standard machine-index renderers enumerate
/// them like any other page.
///
/// File-backed sections flow through Discovery → Loading into `BuildContext.sections`, and
/// every `context`-walking system renderer (`SitemapRenderer`, `NavIndexRenderer`, search
/// index, `LlmsTxtRenderer`) reads them from there. A blueprint whose pages are *generated*
/// (the OpenAPI blueprint builds them from a spec; they never touch the content directory)
/// would otherwise be invisible to those renderers. Conform a provider, register it via
/// `SiteBuilder.contentSectionProvider(_:)`, and the pipeline merges the returned section
/// into the context after file loading – one registration, and sitemap + nav-index + search
/// + llms.txt all include the pages.
///
/// The provider receives the file-backed context (config, router, output directory), so it
/// can compute URLs and slugs the same way the page renderers do; it must not assume any
/// other provider's pages are present. Pair the provider with a `PagePathResolving` when the
/// generated pages live at paths the `URLRouter` cannot derive, so the index renderers link
/// to the URLs that actually ship.
public protocol ContentSectionProviding: Sendable {
   /// Builds the synthetic section to merge into `context`, or `nil` when the provider has
   /// nothing to contribute (e.g. the source spec failed to load).
   func contentSection(in context: BuildContext) -> ContentSection?
}
