import Foundation

/// Renders the Community ↔ AI variant toggle for a DocC note that has both an
/// authored note (`<slug>.md`) and an AI-generated sibling (`<slug>.ai.md`).
///
/// Design (from the spec): **both bodies stay in the DOM** so neither variant is
/// hidden from crawlers/AI (the project's whole point) – radio inputs + CSS only
/// switch which one is *shown*, defaulting to Community. It is fully no-JS (CSS
/// `:checked`), and a distinct class namespace (`sk-docc-variant*` / `sk-docc-mode*`)
/// so it never collides with the in-content `@TabNavigator` notes. When there is no
/// AI variant the community body is returned unchanged (no switcher).
///
/// The toggle is presented as two large "mode" cards (icon + label + subtitle + a
/// check on the active card), the AI card carrying a "BETA" tag and an accent skin
/// hook (`sk-docc-mode--ai`). An AI-only disclaimer banner (`sk-docc-ai-banner`)
/// shows when the AI mode is active. All of this is CSS-driven off the radios.
public struct DocCVariantSwitcher {
   public init() {}

   public func render(community: String, ai: String?, slug: String) -> String {
      // UIStrings-less overload: falls back to bare defaults for callers that
      // do not have a UIStrings instance (e.g. unit tests targeting mechanics).
      self.render(community: community, ai: ai, slug: slug, uiStrings: nil)
   }

   /// Renders the Community↔AI toggle with localised labels drawn from `uiStrings`.
   /// When `uiStrings` is `nil` the English defaults shipped in the prototype are used.
   public func render(community: String, ai: String?, slug: String, uiStrings: UIStrings?) -> String {
      guard let ai, !ai.isEmpty else { return community }
      let s = uiStrings
      let communityLabel = s?.string(for: .doccCommunityLabel) ?? "Community Notes"
      let communitySubtitle = s?.string(for: .doccCommunitySubtitle) ?? "Written & reviewed by people"
      let aiLabel = s?.string(for: .doccAILabel) ?? "AI Notes"
      let aiSubtitle = s?.string(for: .doccAISubtitle) ?? "On-device summary of the video"
      let bannerText = s?.string(for: .doccAIBannerText)
         ?? "AI Notes (beta) are generated by an on-device model from the session transcript. They can be wrong or incomplete. Switch to Community Notes for human-reviewed detail."

      let name = "sk-variant-\(slug)"
      let aiTitleHTML = "\(Self.escape(aiLabel)) <span class=\"sk-docc-beta\">beta</span>"
      return "<div class=\"sk-docc-variants\">"
         + "<input class=\"sk-docc-variant-radio sk-docc-variant-radio-community\" type=\"radio\" name=\"\(name)\" id=\"\(name)-community\" checked/>"
         + "<input class=\"sk-docc-variant-radio sk-docc-variant-radio-ai\" type=\"radio\" name=\"\(name)\" id=\"\(name)-ai\"/>"
         + "<div class=\"sk-docc-modeswitch\" role=\"tablist\" aria-label=\"Note version\">"
         + Self.modeCard(
            for: "\(name)-community",
            kind: "community",
            icon: Self.communityIcon,
            title: Self.escape(communityLabel),
            subtitle: Self.escape(communitySubtitle)
         )
         + Self.modeCard(
            for: "\(name)-ai",
            kind: "ai",
            icon: Self.aiIcon,
            title: aiTitleHTML,
            subtitle: Self.escape(aiSubtitle)
         )
         + "</div>"
         + "<div class=\"sk-docc-ai-banner\" role=\"note\">"
         + "<span class=\"sk-docc-ai-banner-ic\" aria-hidden=\"true\">\(Self.aiIcon)</span>"
         + "<span>\(Self.escape(bannerText))</span>"
         + "</div>"
         + "<div class=\"sk-docc-variant sk-docc-variant-community\">\(community)</div>"
         + "<div class=\"sk-docc-variant sk-docc-variant-ai\">\(ai)</div>"
         + "</div>"
   }

   /// One selectable mode card. It is a `<label>` driving the hidden radio, so the
   /// whole switch stays no-JS. `kind` ("community"/"ai") adds the skin-hook class.
   private static func modeCard(for id: String, kind: String, icon: String, title: String, subtitle: String) -> String {
      let modifier = kind == "ai" ? " sk-docc-mode--ai" : ""
      return "<label class=\"sk-docc-mode\(modifier)\" for=\"\(id)\">"
         + "<span class=\"sk-docc-mode-ic\" aria-hidden=\"true\">\(icon)</span>"
         + "<span class=\"sk-docc-mode-txt\"><b>\(title)</b><span>\(subtitle)</span></span>"
         + "<span class=\"sk-docc-mode-check\" aria-hidden=\"true\">\(Self.checkIcon)</span>"
         + "</label>"
   }

   private static func escape(_ string: String) -> String {
      string
         .replacing("&", with: "&amp;")
         .replacing("\"", with: "&quot;")
         .replacing("<", with: "&lt;")
         .replacing(">", with: "&gt;")
   }

   // Inline SVGs keep the component dependency-free (no FontAwesome requirement) and
   // inherit `currentColor`, so a theme tints them by setting the text/accent color.
   private static let communityIcon =
      "<svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"/><circle cx=\"9\" cy=\"7\" r=\"4\"/><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"/><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"/></svg>"
   private static let aiIcon =
      "<svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"currentColor\"><path d=\"M12 2l1.6 4.6L18 8.2l-4.4 1.6L12 14.4l-1.6-4.6L6 8.2l4.4-1.6L12 2zm6 10l.9 2.5 2.5.9-2.5.9L18 19l-.9-2.7-2.5-.9 2.5-.9.9-2.5zM6 14l.7 2 2 .7-2 .7L6 19.4l-.7-2-2-.7 2-.7.7-2z\"/></svg>"
   private static let checkIcon =
      "<svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"20 6 9 17 4 12\"/></svg>"
}
