import Foundation

/// Pure HTML composer for the `Plugin/themes/ThemePreview.html` comparison
/// grid. Extracted from the driver so the grid composition is unit-testable
/// without running an end-to-end build.
///
/// The driver remains the orchestrator: it computes the variant list and the
/// route list, calls ``ComparisonIndex/html(variants:routes:)`` to produce
/// the document, and writes the result to disk. No file I/O happens here.
public enum ComparisonIndex {
   /// Builds one `.preview-card` block for a single variant × route pair.
   public static func gridTile(for variant: PreviewVariant, route: PreviewRoute) -> String {
      let filename = route.outputFilename(for: variant)
      let href = "preview/\(filename)"
      let titleSuffix = route.label
      let title = "\(variant.layoutTemplate) – \(variant.colorScheme) / \(variant.fontPairing) / \(variant.mode.rawValue) – \(titleSuffix)"
      let params = "colorScheme: \(variant.colorScheme) &middot; fontPairing: \(variant.fontPairing) &middot; \(variant.mode.rawValue) &middot; \(titleSuffix)"
      return """
               <div class="preview-card">
                  <div class="frame-scaler">
                     <iframe src="\(href)" title="\(title)" loading="lazy" scrolling="no"></iframe>
                  </div>
                  <div class="meta">
                     <h3>\(variant.layoutTemplate) – \(titleSuffix)</h3>
                     <div class="params">\(params)</div>
                     <a class="openlink" href="\(href)" target="_blank" rel="noopener">Open full size &rarr;</a>
                  </div>
               </div>
      """
   }

   /// Builds the full `ThemePreview.html` document. Variants are grouped by
   /// layout template; templates are ordered by first appearance in
   /// ``variants`` (so adding a fourth layout no longer requires editing a
   /// hard-coded allow-list – closes M-020 CR Backlog item).
   public static func html(variants: [PreviewVariant], routes: [PreviewRoute]) -> String {
      var seenTemplates: [String] = []
      var grouped: [String: [PreviewVariant]] = [:]
      for variant in variants {
         if grouped[variant.layoutTemplate] == nil {
            seenTemplates.append(variant.layoutTemplate)
         }
         grouped[variant.layoutTemplate, default: []].append(variant)
      }

      var sections: [String] = []
      for template in seenTemplates {
         guard let templateVariants = grouped[template] else { continue }
         let tiles = templateVariants.flatMap { variant in
            routes.map { route in Self.gridTile(for: variant, route: route) }
         }
         sections.append("""
               <h2>\(template)</h2>
               <div class="grid">
         \(tiles.joined(separator: "\n"))
               </div>
         """)
      }
      return Self.documentTemplate(body: sections.joined(separator: "\n"))
   }

   private static func documentTemplate(body: String) -> String {
      """
      <!DOCTYPE html>
      <html lang="en">
      <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>SiteKit Theme Preview</title>
      <!-- Generated by Plugin/themes/generate-previews.swift – do not edit by hand. -->
      <style>
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body {
         font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
         color: #1c1917;
         background: #f5f5f4;
         line-height: 1.6;
         padding: 32px 24px 64px;
         -webkit-font-smoothing: antialiased;
      }
      .page { max-width: 1400px; margin: 0 auto; }
      h1 { font-size: 1.75rem; letter-spacing: -0.02em; margin-bottom: 6px; }
      .subtitle { color: #57534e; margin-bottom: 12px; max-width: 70ch; }
      .hint { color: #78716c; font-size: 0.875rem; margin-bottom: 36px; max-width: 70ch; }
      h2 {
         font-size: 1.25rem;
         margin: 36px 0 16px;
         padding-bottom: 6px;
         border-bottom: 1px solid #e7e5e4;
      }
      .grid {
         display: grid;
         grid-template-columns: repeat(auto-fill, 480px);
         gap: 28px;
         justify-content: center;
      }
      .preview-card {
         border: 1px solid #d6d3d1;
         border-radius: 14px;
         overflow: hidden;
         background: #ffffff;
         box-shadow: 0 1px 3px rgba(0,0,0,0.06);
         max-width: 100%;
      }
      .frame-scaler {
         width: 480px;
         height: 720px;
         overflow: hidden;
         position: relative;
         background: #ffffff;
      }
      .frame-scaler iframe {
         width: 1000px;
         height: 1500px;
         border: 0;
         transform: scale(0.48);
         transform-origin: top left;
      }
      .preview-card .meta {
         padding: 14px 18px 16px;
         border-top: 1px solid #e7e5e4;
         display: flex;
         flex-direction: column;
         gap: 8px;
      }
      .preview-card h3 { margin: 0; font-size: 1rem; }
      .preview-card .params {
         color: #78716c;
         font-size: 0.75rem;
         font-family: "SF Mono", Menlo, Monaco, monospace;
      }
      .preview-card .openlink {
         display: inline-flex;
         align-items: center;
         gap: 0.4rem;
         margin-top: 2px;
         padding: 0.45rem 0.95rem;
         font-size: 0.8125rem;
         font-weight: 600;
         color: #4338ca;
         background: #eef2ff;
         border: 1px solid #c7d2fe;
         border-radius: 999px;
         text-decoration: none;
         align-self: flex-start;
         transition: background 0.15s, border-color 0.15s, color 0.15s;
      }
      .preview-card .openlink:hover {
         background: #e0e7ff;
         border-color: #a5b4fc;
         color: #312e81;
      }
      @media (max-width: 540px) {
         body { padding: 24px 12px 48px; }
         .grid { gap: 16px; grid-template-columns: 1fr; }
         .preview-card, .frame-scaler { width: 100%; }
         .frame-scaler { height: 540px; }
      }
      </style>
      </head>
      <body>
      <div class="page">
         <h1>SiteKit Theme Preview</h1>
         <p class="subtitle">Compare full-layout themes – each layout template shown with a representative color scheme, font pairing, and light/dark mode. Each variant gets a Home tile and an Article tile so the chrome AND the long-form reading experience are side-by-side.</p>
         <p class="hint">Each tile is a complete, self-contained page scaled down to fit. Open a tile in its own tab for a full-size view. Tailshare this file to review the grid from your phone.</p>
      \(body)
      </div>
      </body>
      </html>
      """
   }
}
