import Foundation

/// Generates a Cloudflare Pages `_headers` file with cache-control + security headers.
///
/// Without this, Lighthouse flags "Use efficient cache lifetimes" on every page (typically
/// 2–6s of savings on repeat visits). With it, static assets (CSS, JS, images, fonts) are
/// cached for 1 year, and HTML always revalidates so every deploy is served fresh.
///
/// The `_headers` format is also supported by Netlify. Vercel uses a different format
/// (`vercel.json`) – not generated here; a Vercel equivalent can be added later.
/// On GitHub Pages or other static hosts without header control, this file is simply ignored.
///
/// ### Generated rules
///
/// ```
/// /*                        → HTML: always revalidate (max-age=0); no-sniff, frame-deny, no-referrer-when-downgrade
/// /assets/*.css /assets/*.js → immutable, 1 year (fingerprinted CSS/JS – content hash in the filename)
/// /*.woff2                  → immutable, 1 year (web fonts)
/// /apple-touch-icon.png …   → immutable, 1 year (favicons, fixed root paths)
/// /feed.xml /podcast.xml    → 15 minutes (RSS feeds – recent enough, cheap to refresh)
/// /sitemap.xml /robots.txt  → 1 day
/// ```
///
/// ### Why immutable is scoped to `/assets/*.css` and `/assets/*.js`, not `/assets/*`
///
/// Cloudflare merges the `Cache-Control` of *every* matching rule with a comma and never
/// lets a more specific rule override a broader one, and it allows only a single `*` per
/// rule – so a glob that matches a content-hash segment (`*.<hash>.css`) cannot be
/// expressed. A blanket `/assets/*` immutable rule therefore also stamped `immutable` onto
/// fixed-name *mutable* files that live under `/assets/` – the machine-readable
/// `nav-index.json` / `search-index.json` indexes (refetched at fixed URLs and rewritten
/// every build), the per-section search JSON, and any content images – caching them for a
/// year so returning visitors saw stale navigation and search until the cache expired.
/// `AssetFingerprinter` only ever hashes referenced `/assets/**` CSS and JS, so scoping the
/// immutable rule to those two extensions keeps every fingerprinted file cached forever
/// while letting the mutable JSON indexes and images fall through to the revalidating `/*`
/// rule. The only fixed-name files still matched are emitted-but-unreferenced `base.css` /
/// `tokens.css` (un-hashed precisely because no page links them), which are never served to
/// a browser, so an immutable header on them can never surface stale content.
public struct CloudflareHeadersRenderer: Renderer {
   /// `.global` – the `_headers` file is site-wide, not per locale. The pipeline
   /// routes `.global` renderers through a single invocation, so this file is
   /// written exactly once per build.
   public var scope: RenderScope { .global }

   public init() {}

   public func render(context: BuildContext) throws -> [OutputFile] {
      let content = """
      # Generated by SiteKit – do not edit
      # Cloudflare Pages / Netlify _headers format
      # See: https://developers.cloudflare.com/pages/configuration/headers/

      # Fingerprinted CSS/JS: cache forever (the content hash in the filename changes when the
      # bytes change, so the client fetches a new URL on redeploy). Scoped to .css/.js – the only
      # extensions AssetFingerprinter hashes – so fixed-name mutable files under /assets/ (the
      # nav-index.json / search-index.json indexes, per-section search JSON, content images) fall
      # through to the revalidating /* rule below instead of being pinned for a year. Cloudflare
      # merges same-name headers across all matching rules with no override and allows only one
      # splat per rule, so a single content-hash glob is not expressible; matching the
      # fingerprintable extensions is the precise rule that keeps the mutable indexes off immutable.
      /assets/*.css
         Cache-Control: public, max-age=31536000, immutable
      /assets/*.js
         Cache-Control: public, max-age=31536000, immutable

      # Web fonts (woff2)
      /*.woff2
         Cache-Control: public, max-age=31536000, immutable

      # Favicons and root-level images
      /apple-touch-icon.png
         Cache-Control: public, max-age=31536000, immutable
      /favicon-32x32.png
         Cache-Control: public, max-age=31536000, immutable
      /favicon-16x16.png
         Cache-Control: public, max-age=31536000, immutable
      /favicon.ico
         Cache-Control: public, max-age=31536000, immutable

      # RSS / podcast feeds – keep fresh
      /feed.xml
         Cache-Control: public, max-age=900
      /podcast.xml
         Cache-Control: public, max-age=900

      # Sitemap and robots – 1 day is plenty
      /sitemap.xml
         Cache-Control: public, max-age=86400
      /robots.txt
         Cache-Control: public, max-age=86400
      /llms.txt
         Cache-Control: public, max-age=86400

      # HTML: always revalidate so every deploy is served fresh. max-age=0 marks the response
      # immediately stale, so every cache must check origin before serving it, and
      # must-revalidate forbids serving a stale page on error. Fingerprinted /assets/*.css and
      # /assets/*.js above stay immutable, so this only revalidates the small HTML shell plus the
      # mutable JSON indexes and images – never re-downloading the hashed CSS/JS bundles.
      # Also set a minimal set of security/SEO headers. Nothing aggressive that could break
      # embedded content (iframes from trusted sources, etc.).
      /*
         Cache-Control: public, max-age=0, must-revalidate
         X-Content-Type-Options: nosniff
         Referrer-Policy: strict-origin-when-cross-origin
         X-Frame-Options: SAMEORIGIN

      """

      let outputPath = context.outputDirectory.appendingPathComponent("_headers")
      return [OutputFile(outputPath: outputPath, content: content)]
   }
}
