import Foundation

/// Writes `README.md` index files into the project's content source
/// directories – one per non-empty section – so AI agents can map a content
/// collection by reading a single file.
///
/// Output paths point at `BuildContext.projectDirectory`, not
/// `outputDirectory`. That makes this renderer the rare case of "renderer
/// that writes back into the source tree", because the indexes need to ship
/// with the content for agents reading the repo offline. Read-only against
/// the rendered site; safe to omit if a project does not need agent-readable
/// indexes. Part of the AI-friendliness cross-cutting concern.
public struct ContentIndexRenderer: Renderer {
   public init() {}

   public func render(context: BuildContext) throws -> [OutputFile] {
      var files: [OutputFile] = []

      let contentDir = context.projectDirectory
         .appendingPathComponent(context.config.contentDirectory)

      // Section indexes
      for section in context.sections {
         guard !section.pages.isEmpty else { continue }
         let sectionDir = contentDir.appendingPathComponent(section.config.contentDirectory)
         let readme = self.buildBlogIndex(articles: section.pages, config: context.config)
         files.append(OutputFile(
            outputPath: sectionDir.appendingPathComponent("README.md"),
            content: readme
         ))
      }

      // Pages index
      if !context.staticPages.isEmpty {
         let pagesDir = contentDir.appendingPathComponent("Pages")
         let readme = self.buildPagesIndex(pages: context.staticPages)
         files.append(OutputFile(
            outputPath: pagesDir.appendingPathComponent("README.md"),
            content: readme
         ))
      }

      return files
   }

   // MARK: - Private

   private func buildBlogIndex(articles: [PageModel], config: SiteConfig) -> String {
      let dateFormatter = DateFormatter()
      dateFormatter.dateFormat = "yyyy-MM-dd"

      var lines: [String] = []
      lines.append("# Blog Content Index")
      lines.append("")
      lines.append("**Total Posts:** \(articles.count)")
      lines.append("")

      // Recent posts (last 10)
      lines.append("## Recent Posts (Last 10)")
      for article in articles.prefix(10) {
         let filename = article.sourcePath.lastPathComponent
         let dateStr = article.date.map { dateFormatter.string(from: $0) } ?? "undated"
         let tagStr = article.tags.isEmpty ? "" : " – \(article.tags.map { "#\($0)" }.joined(separator: " "))"
         let summaryStr = article.summary.map { " – \($0)" } ?? ""
         lines.append("- `\(filename)` – \(article.title) (\(dateStr))\(tagStr)\(summaryStr)")
      }
      lines.append("")

      // Posts by year
      let byYear = Dictionary(grouping: articles) { article -> Int in
         guard let date = article.date else { return 0 }
         return Calendar.current.component(.year, from: date)
      }

      let sortedYears = byYear.keys.sorted(by: >)
      if sortedYears.count > 1 {
         lines.append("## Posts by Year")
         for year in sortedYears {
            let count = byYear[year]?.count ?? 0
            let label = year == 0 ? "Undated" : "\(year)"
            lines.append("- **\(label):** \(count) posts")
         }
         lines.append("")
      }

      // Tags summary
      var tagCounts: [String: Int] = [:]
      for article in articles {
         for tag in article.tags {
            tagCounts[tag, default: 0] += 1
         }
      }

      if !tagCounts.isEmpty {
         let sortedTags = tagCounts.sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }
         lines.append("## Tags")
         for (tag, count) in sortedTags.prefix(30) {
            let displayName = config.tagDisplayNames?[tag] ?? tag
            lines.append("- **\(displayName)** (\(count) posts)")
         }
         if sortedTags.count > 30 {
            lines.append("- *...and \(sortedTags.count - 30) more tags*")
         }
         lines.append("")
      }

      // All posts (chronological)
      lines.append("## All Posts (Chronological)")
      for article in articles {
         let filename = article.sourcePath.lastPathComponent
         let dateStr = article.date.map { dateFormatter.string(from: $0) } ?? "undated"
         lines.append("- \(dateStr): `\(filename)` – \(article.title)")
      }
      lines.append("")

      // Auto-generation notice
      lines.append("---")
      lines.append("*Auto-generated by SiteKit ContentIndexRenderer. Do not edit manually.*")
      lines.append("")

      return lines.joined(separator: "\n")
   }

   private func buildPagesIndex(pages: [PageModel]) -> String {
      var lines: [String] = []
      lines.append("# Pages Content Index")
      lines.append("")
      lines.append("**Total Pages:** \(pages.count)")
      lines.append("")

      lines.append("## All Pages")
      for page in pages.sorted(by: { $0.title < $1.title }) {
         let filename = page.sourcePath.lastPathComponent
         lines.append("- `\(filename)` – \(page.title)")
      }
      lines.append("")

      lines.append("---")
      lines.append("*Auto-generated by SiteKit ContentIndexRenderer. Do not edit manually.*")
      lines.append("")

      return lines.joined(separator: "\n")
   }
}
