import Foundation
import Logging
import Yams

/// Generates a Cloudflare Pages `_redirects` file with server-side 301 redirects.
///
/// This is an **optional optimization** on top of `HTMLRedirectPageRenderer`.
/// Both generators read from the same `redirects.yaml` file:
///
/// - `HTMLRedirectPageRenderer` creates HTML meta-refresh redirect pages (works everywhere)
/// - `CloudflareRedirectsRenderer` creates a `_redirects` file (Cloudflare Pages processes
///   these as true HTTP 301s before serving static files, which is faster for SEO)
///
/// When deployed to Cloudflare Pages, the `_redirects` file takes priority – the HTML
/// fallback pages are never served. On other platforms, the HTML pages work as the fallback.
///
/// For other hosting platforms, see SiteKit documentation:
/// - **Netlify**: uses the same `_redirects` format
/// - **Vercel**: uses `vercel.json` with a `redirects` array
/// - **GitHub Pages**: no server-side redirects (HTML fallback only)
public struct CloudflareRedirectsRenderer: Renderer {
   public var scope: RenderScope { .global }

   private let logger = Logger(label: "SiteKit.CloudflareRedirects")

   public init() {}

   public func render(context: BuildContext) throws -> [OutputFile] {
      guard let redirectsFile = context.config.redirectsFile else { return [] }

      let filePath = context.projectDirectory.appendingPathComponent(redirectsFile)
      guard FileManager.default.fileExists(atPath: filePath.path) else { return [] }

      let yamlString = try String(contentsOf: filePath, encoding: .utf8)
      let decoder = YAMLDecoder()
      let config = try decoder.decode(RedirectsFileConfig.self, from: yamlString)

      var lines: [String] = [
         "# Server-side 301 redirects for Cloudflare Pages",
         "# Generated by SiteKit from \(redirectsFile)",
         "# HTML meta-refresh fallback pages also exist for platform portability",
         "",
      ]

      for rule in config.redirects {
         let status = rule.status ?? 301
         lines.append("\(rule.from)  \(rule.to)  \(status)")
      }

      let content = lines.joined(separator: "\n") + "\n"
      let path = context.outputDirectory.appendingPathComponent("_redirects")

      self.logger.info("Generated _redirects with \(config.redirects.count) rules")
      return [OutputFile(outputPath: path, content: content)]
   }
}
